version: '3.9'

services:
  customers-db:
    image: postgres
    mem_limit: 200 M
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: customers
    networks:
      - postgres
    volumes:
      - customers_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  fraud-db:
    image: postgres
    mem_limit: 200 M
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: fraud
    networks:
      - postgres
    volumes:
      - fraud_data:/var/lib/postgresql/data
    ports:
      - "5535:5432"

  notification-db:
    image: postgres
    mem_limit: 200 M
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: notification
    networks:
      - postgres
    volumes:
      - notification_data:/var/lib/postgresql/data
    ports:
      - "5636:5432"

  # RabbitMQ
  rabbit-mq:
    image: bitnami/rabbitmq
    container_name: rabbit-mq
    mem_limit: 250 M
    environment:
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=user
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - 'rabbit_mq_data:/bitnami'
    networks:
      - rmq-backend

  # Zipkin
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    networks:
      - backend
    ports:
      - "9411:9411"

  ms-customers:
    image: worldoflegion/ms-customers:0.0.1
    mem_limit: 200 M
    container_name: ms-customers
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend
      - postgres
      - rmq-backend
    depends_on:
      - zipkin
      - customers-db
      - rabbit-mq
    ports:
      - "8080:8080"

  ms-fraud:
    image: worldoflegion/ms-fraud:0.0.1
    mem_limit: 200 M
    container_name: ms-fraud
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend
      - postgres
    depends_on:
      - zipkin
      - fraud-db
    ports:
      - "8181:8181"

  ms-notification:
    image: worldoflegion/ms-notification:0.0.1
    mem_limit: 200 M
    container_name: ms-notification
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend
      - postgres
      - rmq-backend
    depends_on:
      - zipkin
      - notification-db
      - rabbit-mq
    ports:
      - "8282:8282"

volumes:
  customers_data:
  fraud_data:
  notification_data:
  #    Rabbit MQ
  rabbit_mq_data:
    name: rmq_stats_data
    driver: local

networks:
  postgres:
  backend:
  #    Rabbit MQ
  rmq-backend: