spring:
  application:
    name: notification
  datasource:
    url: jdbc:postgresql://notification-db:5432/notification
    password: user
    username: user
    driver-class-name: org.postgresql.Driver
#  JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    show-sql: true
#   Rabbit
  rabbitmq:
    addresses: rabbit-mq:5672
    host: rabbit-mq
    port: 15672
    username: user
    password: user
  #    Zipkin
  zipkin:
    base-url: http://zipkin:9411/

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

server:
  port: 8282

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key