spring:
  application:
    name: notification
  datasource:
    url: jdbc:postgresql://postgres:5432/notifications
    password: pass
    username: users
    driver-class-name: org.postgresql.Driver
#  JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    show-sql: true
#   Rabbit
  rabbitmq:
    addresses: rabbitmq:5672
    host: rabbitmq
    port: 15672
    username: guest
    password: guest
  #    Zipkin
  zipkin:
    base-url: http://zipkin:9411/

server:
  port: 8282

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key