spring:
  application:
    name: fraud
  datasource:
    url: jdbc:postgresql://fraud-db:5432/fraud
    password: user
    username: user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    show-sql: true
  zipkin:
    base-url: http://zipkin:9411

server:
  port: 8181

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
