spring:
  application:
    name: fraud
  datasource:
    url: jdbc:postgresql://postgres:5432/frauds
    password: pass
    username: users
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    show-sql: true
  zipkin:
    base-url: http://zipkin:9411

server:
  port: 8181