spring:
  application:
    name: apigw
  cloud:
    gateway:
      routes:
        - id: customers
          uri: lb://CUSTOMERS
          predicates:
            - Path=/v1/customers/**
        - id: fraud
          uri: lb://FRAUD
          predicates:
            - Path=/v1/fraud-check/**
  zipkin:
    base-url: http://zipkin:9411/

server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

