spring:
  application:
    name: customers
  datasource:
    url: jdbc:postgresql://postgres:5432/customers
    password: pass
    username: users
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    show-sql: true

  # RabbitMQ
  rabbitmq:
    addresses: rabbitmq:5672
    host: rabbitmq
    port: 15672
    username: guest
    password: guest

  zipkin:
    base-url: http://zipkin:9411

#endpoints:
#  ms-fraud: http://localhost:8181

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key